# Generated by Django 4.0.4 on 2022-04-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy_vendor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='release_date',
        ),
    ]
